project:
  type: website
  output-dir: docs

website:
  title: "PPOL-6801"
  favicon: logo_gtown.png
  navbar:
    logo: logo_gtown.png
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Weekly Material
      - href: finalproject.qmd
        text: Final Project
      
format:
  html:
    theme: 
      - cosmo        # base Bootswatch theme
      - style.scss  # your overrides in SCSS
    toc: true
    
editor: visual

