---
title: "PPOL 6801: Text as Data - Computational Linguistics"
subtitle: "McCourt School for Public Policy, Georgetown University"
---

## Course Description

This course introduces students to the quantitative analysis of text as data. With the increasing availability of large-scale textual data – from government documents and political speeches to social media and online news – the potential to extract meaningful insights from text has expanded dramatically. In this course, students will learn to transform text into data and apply it to social science questions and theories. The focus is on understanding the real-world use of text as data, through a large collection of recent academic articles, rather than just the mathematical and computational theory behind it, which we will definitely cover.

The class content can be broadly split into two parts. First, we start with traditional approaches that model text as data using a bag-of-words assumption. Here, we'll cover various methods, including building and utilizing dictionaries, understanding sentiment in text, scaling texts on ideological and policy dimensions, and applying machine learning to classify text. In the second half of the class, we will focus on state-of-the-art models that move beyond bag-of-words and sparse representations of text, and model text based on embeddings/dense representations of words. Here, we begin with an overview of how to represent text as data, from sparse representations via bag-of-words models to dense representations using word embeddings. We then discuss the use of deep learning models for text representation and downstream classification tasks. From here, we will discuss the foundation of the state-of-the-art machine learning models for text analysis: transformer models. Lastly, we will discuss several applications of large language models in social science tasks.

The course includes hands-on exercises using real-world data to reinforce lecture content. By the end, students will have a toolkit for text analysis that is useful in roles such as policy experts and computational social scientists. Students should have completed at least an introductory statistics course and have a basic understanding of probability, distributions, hypothesis testing, and linear models. Students are also expected to have experience working with R, the programming language and software environment used in this course, and Python for the LLM components of the course.

## Class Website

<https://tiagoventura.github.io/PPOL_6801/>

## Instructor

[Professor Tiago Ventura](https://www.venturatiago.com/)

-   Pronouns: He/Him
-   Email: [tv186\@georgetown.edu](mailto:tv186@georgetown.edu)
-   Lectures: Every Monday, 9:30am - 12pm
-   Office Hours: Every Tuesday, 3pm - 4pm
    -   Location: McCourt Building, 766

## Office Hours

**You are all welcome to the office hours.** You can come to the office hours to:

-   Drink some coffee;

-   Ask what I am doing research at;

-   Tell me about your research;

-   Ask any question about our class;

-   Or just talk about soccer.

All are valid options! And no need to schedule time with me!

## Course Infra-structure

**Class Website:** This class website will be used throughout the course and should be checked on a regular basis for lecture materials and required readings.

**Class Slack Channel:** The class also has a dedicated [slack channel](https://join.slack.com/t/ppol68012025/shared_invite/zt-3c33fiq9f-_YQ2c1p660cGIk~zLyaH7Q). The channel serves as an open forum to discuss, collaborate, pose problems/questions, and offer solutions. Students are encouraged to pose any questions they have there as this will provide the professor the means of answering the question so that all can see the response. If you're unfamiliar with, please consult the following start-up tutorial <https://get.slack.help/hc/en-us/articles/218080037-Getting-started-for-new-members>. Please follow the [invite link](https://join.slack.com/t/ppol68012025/shared_invite/zt-3c33fiq9f-_YQ2c1p660cGIk~zLyaH7Q) to be added to the Slack channel.

**Canvas:** A Canvas site <http://canvas.georgetown.edu> will be used throughout the course and should be checked on a regular basis for announcements. Materials will be posted here, and not on canvas, or distributed in class or by e-mail. Support for Canvas is available at (202) 687-4949

## Credits

To build this course, I used materials from Arthur Spirling [Text-as-Data](https://github.com/ArthurSpirling/text-as-data-class-spring2021) Class at NYU, and lab materials from various TA's for his course ([Elisa Wirsching](https://elisawirsching.github.io/), [Lucia Motolinia](https://sites.wustl.edu/luciamotolinia/), [Pedro L. Rodriguez](http://prodriguezsosa.com/), [Kevin Munger](http://www.kevinmunger.com/), [Patrick Chester](https://patrickjchester.com/), [Leslie Huang](https://leslie-huang.github.io/)), Pablo Barbera's [Computational Social Science Seminar](http://pablobarbera.com/POIR613/index.html) seminar, [Brandon Stewart](https://bstewart.scholar.princeton.edu/), [Alex Siegel](https://aasiegel.github.io/website/website-main/), [Chris Bail](https://www.chrisbail.net/), [Sebastian Vallejo](https://www.svallejovera.com/), among others. Their lessons and inspiration are spread throughout all the materials of the course. Thanks!
