---
title: "Weekly Materials & Readings"
subtitle: "Data Science and Public Policy, McCourt School for Public Polcy, Georgetown University"
---

## Week 1, September 2nd

-   **Topics:** Course overview, logistics, introduction to R

-   **Lecture**: [Week 1 - Introduction](/slides/week_01_intro.html)

-   **Coding Materials**: <a href="/code/week1_intro_to_R.R" download> Week 1 - Introduction to R </a>

-   **Data:** [Pooling Data](https://www.dropbox.com/scl/fi/2j5wmwtgvsis4eul89as2/national_clinton_trump_6_20_2016.csv?rlkey=yh2ziddv1ixajunkompwepz6f&dl=0)

## Week 2, September 8th

-   **Topics:** How to represent text as data, Bag of Words Assumption, Tokens and Pre-Processing

-   **Lecture**: [Week 2 - From Text to Matrices: Representing Text as Data](/slides/week_02.html)

-   **Coding Materials**: <a href="/code/week2_introduction_to_text_analysis.R" download> Week 2 - Text Data Processing </a>

-   **Data**:

    -   [Tweets from Elections](https://www.dropbox.com/scl/fi/mj8ldtyqwpkelnpyv0aja/tweets_congress.csv?rlkey=oltuf3odk3trrwjfl0a6ka25t&dl=0)

## Week 3, September 15

-   **Topics:** vector space model, comparing documents, textual complexity.

-   **Lecture**: [Week 3 - Descriptive Inference](/slides/week_03.html)

-   **Coding Materials**: <a href="/code/week3_descriptive_inference.R" download> Week 3 - Descriptive Inference </a>

## Week 4: September 22

-   **Topics:** Dictionaries, Pros and Cons, and Using Off-the-Shelf Models

-   **Lecture:** [Week 4 - Dictionaries and Off-the-Shelf Classifiers](/slides/week_04.html)

-   **Coding Materials:**

    -   <a href="/code/week4_dictionaries.R" download> Week 4 - Dictionaries and Off-the-Shelf Classifiers</a>

    -   <a href="/code/_week4_transformers.ipynb" download> Week 4 - Transformers Based Classifiers </a>

    -   <a href="/code/week4_transformers.qmd" download> Week 4 - Transformers Based Classifiers in R </a>, [html here](/code/week4_transformers.html)

-   **Data:** [Streamming Chat Comments](https://www.dropbox.com/scl/fi/efgllmfeyo5rhnvblq9ki/comments_facebook_presidental_elections.csv?rlkey=aqebsrcf5sb63txetovb9nnkc&dl=0)

## Week 5: September 29

-   **Topics**: Building a training data, regularization, model selection, and model evaluation.

-   **Lecture**: [Week 5 - Supervised Learning](/slides/week_05.html)

-   **Coding Materials**: <a href="/code/week5_supervised_learning.R" download> Week 5 - Supervised Learning: Training your own classifiers</a>

## Week 6: October 6

-   **Topics**: Unsupervised learning, topic models, and clustering

-   **Lecture**: [Week 6 - Unsupervised Learning](/slides/week_06.html)

-   **Coding Materials**: <a href="/code/week6_unsupervised_learning.R" download> Week 7 - Unsupervised Learning: Topic Models</a>

## Week 7: October 20

-   **Topics**: Unsupervised learning + Scaling

-   **Lecture**: [Week 7 - Scaling](/slides/week_10.html)

-   **Coding Materials**: <a href="/code/week10_scaling.R" download> Week 10 - Scaling</a>

## Week 8: October 27

-   **Topics**: Introduction to Deep Learning

-   **Lecture**: [Week 8 - Deep Learning](/slides/week_8.html)

-   **Coding Materials (OPTIONAL)**:

    -   [Logistic Regression as a Neural Network](https://colab.research.google.com/drive/1_MeUXbm2-L2QCMnn0CJcmzSexxDYUWVf?usp=sharing)

    -   [Introduction to Pytorch](https://docs.pytorch.org/tutorials/beginner/introyt/introyt1_tutorial.html)

## Week 9: November 3

-   **Topics**: Word Embeddings - Theory

-   **Lecture**: [Week 9 - Word embeddings](/slides/week_9.html)

-   **Coding Materials in R**:

    -   <a href="/code/week7_word_embeddings.R" download> Week 9 - Word Embeddings in R </a>

-   **Coding Materials in Python (Optional)**

    -   Word Vectors with Gensim: <a href="https://www.dropbox.com/scl/fi/v5ld2gpswxb2tmyezwyx4/_day2_word_vectors.ipynb?rlkey=2eb88oe4dme7f57c60rimbtke&dl=0" download> notebook </a>

## Week 10: November 10

-   **Topics**: Word Embeddings - Applied Paper

-   **Lecture**: [Week 10 - Word embeddings II](/slides/week_10.html)

-   **Coding Materials in R**:

    -   <a href="/code/week7_word_embeddings.R" download> Week 9 - Word Embeddings in R </a>

-   **Coding Materials in Python (Optional)**

    -   Word Vectors with Gensim: <a href="https://www.dropbox.com/scl/fi/v5ld2gpswxb2tmyezwyx4/_day2_word_vectors.ipynb?rlkey=2eb88oe4dme7f57c60rimbtke&dl=0" download> notebook </a>
    
## Week 11: November 17

- **Topics**: Replication Class

- **Materials**: Check the paper your colleagues are replication [here](https://docs.google.com/spreadsheets/d/1gLkGc7wSUcWsH97sdE_8yPoxyEPpPpnpyzCPBS4z8Ig/edit?gid=0#gid=0)


